In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [13]:
df = pd.read_csv("A:\\Machine Learning\\hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [14]:
df.experience = df.experience.fillna('zero')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [15]:
from word2number import w2n
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [16]:
import math
test_score_median = math.floor(df['test_score(out of 10)'].median())
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(test_score_median)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [19]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [20]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [21]:
reg.intercept_

np.float64(17737.263464337688)

In [31]:
dp = pd.read_csv("A:\\Machine Learning\\HiringToPredict.csv")
dp

experience  test_score(out of 10)  interview_score(out of 10)
0           2                      6                          10
1           4                      9                           8
2           1                      8                           9
3           4                      7                           8
4           3                      9                           8

In [32]:
dp['price($)'] = reg.predict(dp)
dp

experience  test_score(out of 10)  interview_score(out of 10)      price($)
0           2                      6                          10  56489.810771
1           4                      9                           8  63242.358079
2           1                      8                           9  55163.027656
3           4                      7                           8  59550.946143
4           3                      9                           8  60429.403202

In [33]:
dp.to_csv("A:\\Machine Learning\\HiringPredicted.csv",index=False)

In [34]:
#Excercise
#Prediction 1: 2yr Experience, 9 test_score, 6 interview_score
reg.predict([[2,9,6]])

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [35]:
#Prediction 2: 12yr Experience, 10 test_score, 10 interview_score
reg.predict([[12,10,10]])

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])